version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/humanetools/orbit/internal/version.Version={{.Version}}
      - -X github.com/humanetools/orbit/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/humanetools/orbit/internal/version.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: humanetools
      name: homebrew-tap
    homepage: "https://github.com/humanetools/orbit"
    description: "Unified CLI for monitoring services across cloud platforms"
    license: "Apache-2.0"
    install: |
      bin.install "orbit"
    test: |
      system "#{bin}/orbit", "--version"
